name: Nuclia Sync

on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install requirements
      run: |
        pip install -q -r requirements-initial.txt
        pip install -q -r requirements.txt
    - name: Run Nuclia Sync
      run: |
        python3 upload.py
    - name: Commit changes
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add .
        git commit -m "Nuclia Sync: Updated docs"
        git push